version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:latest
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Test
          command: dotnet test
      - run:
          name: Run SonarQube analysis
          command: |
            dotnet tool install --global dotnet-sonarscanner
            dotnet sonarscanner begin /k:"APDS_ICE_1" /o:"your_organization" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="your_project_token"
            dotnet build
            dotnet sonarscanner end /d:sonar.login="your_project_token"
